/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ClienteDAO;
import Model.Cliente;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaop
 */
public class ClienteView extends javax.swing.JInternalFrame {
    Cliente cliente;
    ClienteDAO clienteDAO;
    List<Cliente> listaCliente;
    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        clienteDAO = new ClienteDAO();
        listaCliente = new ArrayList<>();
        initComponents();
        this.setVisible(true);
        atualizarTabelaCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Cliente = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_idCliente = new javax.swing.JTextField();
        txt_nomeCliente = new javax.swing.JTextField();
        txt_tipoPessoa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_cpfCliente = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_cnpjCliente = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_emailCliente = new javax.swing.JTextField();
        txt_fone1Cliente = new javax.swing.JFormattedTextField();
        txt_fone2Cliente = new javax.swing.JFormattedTextField();
        txt_fone3Cliente = new javax.swing.JFormattedTextField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_ruaCliente = new javax.swing.JTextField();
        txt_num_enderecoCliente = new javax.swing.JTextField();
        txt_bairroCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Cliente = new javax.swing.JTable();
        btn_Cadastrar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setTitle("MENU CLIENTE");

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 153, 255));
        label1.setText("MENU DE ACESSO A DADOS DE CLIENTE");

        label2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(153, 153, 153));
        label2.setText("Cadastros, buscas e exclusões são realizadas nesta área!");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("NOME:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("TIPO DE PESSOA:");

        txt_idCliente.setEnabled(false);

        txt_nomeCliente.setEnabled(false);

        txt_tipoPessoa.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("CPF:");

        try {
            txt_cpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpfCliente.setEnabled(false);
        txt_cpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpfClienteActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("CNPJ:");

        try {
            txt_cnpjCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cnpjCliente.setEnabled(false);
        txt_cnpjCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cnpjClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nomeCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cnpjCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cnpjCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("EMAIL:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("FONE(1):");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("FONE(2):");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("FONE(3):");

        txt_emailCliente.setEnabled(false);

        try {
            txt_fone1Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fone1Cliente.setEnabled(false);

        try {
            txt_fone2Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fone2Cliente.setEnabled(false);

        try {
            txt_fone3Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fone3Cliente.setEnabled(false);

        label3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(153, 153, 153));
        label3.setText("opcional!");

        label4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(153, 153, 153));
        label4.setText("opcional!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_emailCliente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fone3Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fone1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fone2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fone1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_fone2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fone3Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("RUA:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("NÚMERO:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("BAIRRO:");

        txt_ruaCliente.setEnabled(false);

        txt_num_enderecoCliente.setEnabled(false);

        txt_bairroCliente.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ruaCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_num_enderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bairroCliente)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ruaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_num_enderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Cliente);

        btn_Cadastrar.setBackground(new java.awt.Color(102, 153, 255));
        btn_Cadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Cadastrar.setText("CADASTRAR");
        btn_Cadastrar.setEnabled(false);
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        btn_Buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Buscar.setText("BUSCAR");
        btn_Buscar.setEnabled(false);
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        btn_Editar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Editar.setText("EDITAR");
        btn_Editar.setEnabled(false);
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_Limpar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Limpar.setText("LIMPAR E CANCELAR");
        btn_Limpar.setEnabled(false);
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        btn_Excluir.setBackground(new java.awt.Color(255, 51, 51));
        btn_Excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Excluir.setText("EXCLUIR");
        btn_Excluir.setEnabled(false);
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btn_novo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_novo.setText("NOVO");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ClienteLayout = new javax.swing.GroupLayout(pnl_Cliente);
        pnl_Cliente.setLayout(pnl_ClienteLayout);
        pnl_ClienteLayout.setHorizontalGroup(
            pnl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_ClienteLayout.createSequentialGroup()
                        .addComponent(btn_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_ClienteLayout.setVerticalGroup(
            pnl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pnl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
        String cod = JOptionPane.showInputDialog("Digite o Codigo do Cliente");
        cliente = new Cliente();
        try {
            cliente = clienteDAO.buscaClienteCodigo(cod);
        } catch (SQLException ex) {
            Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txt_nomeCliente.setText(cliente.getNomeCliente());
        txt_tipoPessoa.setText(cliente.getTipoPessoa());
        txt_cpfCliente.setText(cliente.getCpfCliente());
        txt_cnpjCliente.setText(cliente.getCnpjCliente());
        txt_emailCliente.setText(cliente.getEmail());
        txt_fone1Cliente.setText(cliente.getFone1());
        txt_fone2Cliente.setText(cliente.getFone2());
        txt_fone3Cliente.setText(cliente.getFone3());
        txt_ruaCliente.setText(cliente.getRuaCliente());
        txt_num_enderecoCliente.setText(String.valueOf(cliente.getNum_enderecoCliente()));
        txt_bairroCliente.setText(cliente.getBairroCliente());
        
    }//GEN-LAST:event_btn_BuscarActionPerformed

    
    
    
    
    private void txt_cpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpfClienteActionPerformed
        // TODO add your handling code here:
      txt_cnpjCliente.setText("");
    }//GEN-LAST:event_txt_cpfClienteActionPerformed

    private void txt_cnpjClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cnpjClienteActionPerformed
        // TODO add your handling code here:    
       txt_cpfCliente.setText("");
    }//GEN-LAST:event_txt_cnpjClienteActionPerformed

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        // TODO add your handling code here:
        if(txt_nomeCliente.getText().isEmpty() || txt_tipoPessoa.getText().isEmpty() || txt_emailCliente.getText().isEmpty()
        || txt_fone1Cliente.getText().isEmpty() || txt_ruaCliente.getText().isEmpty() || txt_num_enderecoCliente.getText().isEmpty()
        || txt_bairroCliente.getText().isEmpty() ){
                
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatorios!!");
            
        }
        else{
        
            cliente = new Cliente();
            cliente.setNomeCliente(txt_nomeCliente.getText());
            cliente.setTipoPessoa(txt_tipoPessoa.getText());
            cliente.setCpfCliente(txt_cpfCliente.getText());
            cliente.setCnpjCliente(txt_cnpjCliente.getText());
            cliente.setEmail(txt_emailCliente.getText());
            cliente.setFone1(txt_fone1Cliente.getText());
            cliente.setFone2(txt_fone2Cliente.getText());
            cliente.setFone3(txt_fone3Cliente.getText());
            cliente.setRuaCliente(txt_ruaCliente.getText());
            cliente.setNum_enderecoCliente(Integer.parseInt(txt_num_enderecoCliente.getText()));
            cliente.setBairroCliente(txt_bairroCliente.getText());
            
            try {
                clienteDAO.Cadastrar(cliente);
            } catch (SQLException ex) {
                Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso");
            LimpaCamposCliente();
            atualizarTabelaCliente();
            preparaSalvareCancelar();
            desativaCampos();
        }
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        // TODO add your handling code here:
        LimpaCamposCliente();
        preparaSalvareCancelar();
    }//GEN-LAST:event_btn_LimparActionPerformed

    
    
    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        // TODO add your handling code here:
        if(txt_idCliente.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "Selecione um Cliente!!");
        }
        else{
        
            cliente = new Cliente();
            cliente.setCodCliente(Integer.parseInt(txt_idCliente.getText()));
            int confirma = JOptionPane.showConfirmDialog(null,"Deseja Excluir: " + txt_nomeCliente.getText());
            if(confirma == 0){
                try {
                    clienteDAO.Excluir(cliente);
                } catch (SQLException ex) {
                    Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!!");
                LimpaCamposCliente();
                atualizarTabelaCliente();
                
            }
        }
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        // TODO add your handling code here:
        if(txt_idCliente.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um Cliente");
        }
        else if(txt_nomeCliente.getText().isEmpty() || txt_tipoPessoa.getText().isEmpty() || txt_emailCliente.getText().isEmpty()
        || txt_fone1Cliente.getText().isEmpty() || txt_ruaCliente.getText().isEmpty() || txt_num_enderecoCliente.getText().isEmpty()
        || txt_bairroCliente.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para realizar a alteração!!");
        }
        else{
        
            cliente = new Cliente();
            cliente.setNomeCliente(txt_nomeCliente.getText());
            cliente.setTipoPessoa(txt_tipoPessoa.getText());
            cliente.setCpfCliente(txt_cpfCliente.getText());
            cliente.setCnpjCliente(txt_cnpjCliente.getText());
            cliente.setEmail(txt_emailCliente.getText());
            cliente.setFone1(txt_fone1Cliente.getText());
            cliente.setFone2(txt_fone2Cliente.getText());
            cliente.setFone3(txt_fone3Cliente.getText());
            cliente.setRuaCliente(txt_ruaCliente.getText());
            cliente.setNum_enderecoCliente(Integer.parseInt(txt_num_enderecoCliente.getText()));
            cliente.setBairroCliente(txt_bairroCliente.getText());
            cliente.setCodCliente(Integer.parseInt(txt_idCliente.getText()));
            try {
                clienteDAO.Alterar(cliente);
            } catch (SQLException ex) {
                Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
            LimpaCamposCliente();
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!!");
            atualizarTabelaCliente();
            preparaSalvareCancelar();
            desativaCampos();
        }
    }//GEN-LAST:event_btn_EditarActionPerformed

    
    
    private void tbl_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ClienteMouseClicked
        // TODO add your handling code here:
        txt_idCliente.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 0).toString());
        txt_nomeCliente.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 1).toString());
        txt_tipoPessoa.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 2).toString());
        txt_cpfCliente.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 3).toString());
        txt_cnpjCliente.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 4).toString());
        txt_emailCliente.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 5).toString());
        txt_fone1Cliente.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 6).toString());
        txt_fone2Cliente.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 7).toString());
        txt_fone3Cliente.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 8).toString());
        txt_ruaCliente.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 9).toString());
        txt_num_enderecoCliente.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 10).toString());
        txt_bairroCliente.setText(tbl_Cliente.getValueAt(tbl_Cliente.getSelectedRow(), 11).toString());
        preparaSelecaoTabela();
    }//GEN-LAST:event_tbl_ClienteMouseClicked

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
        preparaNovo();
        ativaCampos();
        LimpaCamposCliente();
    }//GEN-LAST:event_btn_novoActionPerformed

    
    public void atualizarTabelaCliente(){
    
        cliente = new Cliente();
        try {
            listaCliente = clienteDAO.ListaCliente();
        } catch (SQLException ex) {
            Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String dados[][] = new String[listaCliente.size()][12];
        int i = 0;
        for (Cliente cliente : listaCliente) {
        
            dados[i][0] = String.valueOf(cliente.getCodCliente());
            dados[i][1] = cliente.getNomeCliente();
            dados[i][2] = cliente.getTipoPessoa();
            dados[i][3] = cliente.getCpfCliente();
            dados[i][4] = cliente.getCnpjCliente();
            dados[i][5] = cliente.getEmail();
            dados[i][6] = cliente.getFone1();
            dados[i][7] = cliente.getFone2();
            dados[i][8] = cliente.getFone3();
            dados[i][9] = cliente.getRuaCliente();
            dados[i][10] = String.valueOf(cliente.getNum_enderecoCliente());
            dados[i][11] = cliente.getBairroCliente();
            i++;
        }
        String tituloColuna[] = {"id","Nome","Tipo Pessoa","CPF","CNPJ","Email","Fone 1","Fone 2","Fone 3","Rua","Numero","Bairro"};
        DefaultTableModel tabelaCliente = new DefaultTableModel();
        tabelaCliente.setDataVector(dados, tituloColuna);
        tbl_Cliente.setModel(new DefaultTableModel(dados,tituloColuna){
        
            boolean[] canEdit = new boolean[]{
            
                false,false,false,false,false,false,false,false,false,false,false,false
            };
            
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        });
        
        tbl_Cliente.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbl_Cliente.getColumnModel().getColumn(1).setPreferredWidth(300);
        tbl_Cliente.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbl_Cliente.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbl_Cliente.getColumnModel().getColumn(4).setPreferredWidth(200);
        tbl_Cliente.getColumnModel().getColumn(5).setPreferredWidth(300);
        tbl_Cliente.getColumnModel().getColumn(6).setPreferredWidth(150);
        tbl_Cliente.getColumnModel().getColumn(7).setPreferredWidth(150);
        tbl_Cliente.getColumnModel().getColumn(8).setPreferredWidth(150);
        tbl_Cliente.getColumnModel().getColumn(9).setPreferredWidth(200);
        tbl_Cliente.getColumnModel().getColumn(10).setPreferredWidth(100);
        tbl_Cliente.getColumnModel().getColumn(11).setPreferredWidth(200);
        
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        tbl_Cliente.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tbl_Cliente.setRowHeight(25);
        tbl_Cliente.updateUI();
    }
    
    
    public void LimpaCamposCliente(){
        
        txt_idCliente.setText("");
        txt_nomeCliente.setText("");
        txt_tipoPessoa.setText("");
        txt_cpfCliente.setText("");
        txt_cnpjCliente.setText("");
        txt_emailCliente.setText("");
        txt_fone1Cliente.setText("");
        txt_fone2Cliente.setText("");
        txt_fone3Cliente.setText("");
        txt_ruaCliente.setText("");
        txt_num_enderecoCliente.setText("");
        txt_bairroCliente.setText("");
        
    }
    
    public void ativaCampos(){
    
     
        txt_nomeCliente.setEnabled(true);
        txt_tipoPessoa.setEnabled(true);
        txt_cpfCliente.setEnabled(true);
        txt_cnpjCliente.setEnabled(true);
        txt_emailCliente.setEnabled(true);
        txt_fone1Cliente.setEnabled(true);
        txt_fone2Cliente.setEnabled(true);
        txt_fone3Cliente.setEnabled(true);
        txt_ruaCliente.setEnabled(true);
        txt_num_enderecoCliente.setEnabled(true);
        txt_bairroCliente.setEnabled(true);
    }
    
    public void desativaCampos(){
    
        txt_idCliente.setEnabled(false);
        txt_nomeCliente.setEnabled(false);
        txt_tipoPessoa.setEnabled(false);
        txt_cpfCliente.setEnabled(false);
        txt_cnpjCliente.setEnabled(false);
        txt_emailCliente.setEnabled(false);
        txt_fone1Cliente.setEnabled(false);
        txt_fone2Cliente.setEnabled(false);
        txt_fone3Cliente.setEnabled(false);
        txt_ruaCliente.setEnabled(false);
        txt_num_enderecoCliente.setEnabled(false);
        txt_bairroCliente.setEnabled(false);
    }
    
    public void preparaNovo(){
    
        btn_novo.setEnabled(false);
        btn_Cadastrar.setEnabled(true);
        btn_Limpar.setEnabled(true);
        btn_Editar.setEnabled(false);
        tbl_Cliente.setEnabled(false);
        tbl_Cliente.clearSelection();
    }
    public void preparaSalvareCancelar(){
     
        btn_novo.setEnabled(true);
        btn_Cadastrar.setEnabled(false);
        btn_Limpar.setEnabled(false);
        btn_Editar.setEnabled(false);
        btn_Excluir.setEnabled(false);
        tbl_Cliente.setEnabled(true);
    }
    
    public void preparaSelecaoTabela(){
    
        btn_novo.setEnabled(true);
        btn_Excluir.setEnabled(true);
        btn_Editar.setEnabled(true);
        btn_Limpar.setEnabled(true);
        ativaCampos();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_novo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JPanel pnl_Cliente;
    private javax.swing.JTable tbl_Cliente;
    private javax.swing.JTextField txt_bairroCliente;
    private javax.swing.JFormattedTextField txt_cnpjCliente;
    private javax.swing.JFormattedTextField txt_cpfCliente;
    private javax.swing.JTextField txt_emailCliente;
    private javax.swing.JFormattedTextField txt_fone1Cliente;
    private javax.swing.JFormattedTextField txt_fone2Cliente;
    private javax.swing.JFormattedTextField txt_fone3Cliente;
    private javax.swing.JTextField txt_idCliente;
    private javax.swing.JTextField txt_nomeCliente;
    private javax.swing.JTextField txt_num_enderecoCliente;
    private javax.swing.JTextField txt_ruaCliente;
    private javax.swing.JTextField txt_tipoPessoa;
    // End of variables declaration//GEN-END:variables
}
