/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import DAO.FuncionarioDAO;
import DAO.UsuarioDAO;
import Model.Funcionario;
import Model.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaop
 */
public class FuncionarioView extends javax.swing.JInternalFrame {
    Funcionario funcionario;
    FuncionarioDAO funcionarioDAO;
    List<Funcionario> listaFuncionario;
    Usuario usuario;
    UsuarioDAO usuarioDAO;
    /**
     * Creates new form FuncionarioView
     */
    public FuncionarioView() {
        funcionarioDAO = new FuncionarioDAO();
        listaFuncionario = new ArrayList<>();
        initComponents();
        this.setVisible(true);
        atualizarTabelaFuncionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Funcionario = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_idFuncionario = new javax.swing.JTextField();
        txt_nomeFuncionario = new javax.swing.JTextField();
        txt_num_carteiraFuncionario = new javax.swing.JFormattedTextField();
        txt_funcaoFuncionario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        txt_foneFuncionario = new javax.swing.JFormattedTextField();
        txt_emailFuncionario = new javax.swing.JTextField();
        txt_senhaFuncionario = new javax.swing.JPasswordField();
        label4 = new java.awt.Label();
        btn_Cadastrar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Funcionario = new javax.swing.JTable();
        btn_novo = new javax.swing.JButton();

        setClosable(true);
        setTitle("MENU FUNCIONÁRIO");
        setPreferredSize(new java.awt.Dimension(909, 692));

        pnl_Funcionario.setPreferredSize(new java.awt.Dimension(842, 692));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 153, 255));
        label1.setText("MENU DE ACESSO A DADOS DE FUNCIONÁRIO");

        label2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(153, 153, 153));
        label2.setText("Cadastros, buscas e exclusões são realizadas nesta área!");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("NOME:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Nº DA CARTEIRA:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("FUNÇÃO:");

        txt_idFuncionario.setEnabled(false);

        txt_nomeFuncionario.setEnabled(false);

        try {
            txt_num_carteiraFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_num_carteiraFuncionario.setEnabled(false);

        txt_funcaoFuncionario.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_idFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_funcaoFuncionario))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_num_carteiraFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_num_carteiraFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_funcaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("FONE:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("EMAIL:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("SENHA:");

        label3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(153, 153, 153));
        label3.setText("Email e senha serão utilizados para login no PDV");

        try {
            txt_foneFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_foneFuncionario.setEnabled(false);

        txt_emailFuncionario.setEnabled(false);

        txt_senhaFuncionario.setEnabled(false);

        label4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(153, 153, 153));
        label4.setText("A senha deve conter no MÁXIMO 8 números");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_senhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_foneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_emailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_foneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_senhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_Cadastrar.setBackground(new java.awt.Color(102, 153, 225));
        btn_Cadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Cadastrar.setText("CADASTRAR");
        btn_Cadastrar.setEnabled(false);
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        btn_Buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Buscar.setText("BUSCAR");
        btn_Buscar.setEnabled(false);
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        btn_Editar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Editar.setText("EDITAR");
        btn_Editar.setEnabled(false);
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_Limpar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Limpar.setText("LIMPAR E CANCELAR");
        btn_Limpar.setActionCommand("LIMPAR ");
        btn_Limpar.setEnabled(false);
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        btn_Excluir.setBackground(new java.awt.Color(255, 51, 51));
        btn_Excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Excluir.setText("EXCLUIR");
        btn_Excluir.setEnabled(false);
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        tbl_Funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_FuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Funcionario);

        btn_novo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_novo.setText("NOVO");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_FuncionarioLayout = new javax.swing.GroupLayout(pnl_Funcionario);
        pnl_Funcionario.setLayout(pnl_FuncionarioLayout);
        pnl_FuncionarioLayout.setHorizontalGroup(
            pnl_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_FuncionarioLayout.createSequentialGroup()
                        .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_FuncionarioLayout.setVerticalGroup(
            pnl_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FuncionarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        // TODO add your handling code here:
      if( txt_nomeFuncionario.getText().isEmpty() || txt_num_carteiraFuncionario.getText().isEmpty()
      || txt_funcaoFuncionario.getText().isEmpty() || txt_foneFuncionario.getText().isEmpty() || txt_emailFuncionario.getText().isEmpty()
      || txt_senhaFuncionario.getText().isEmpty()){
      
          JOptionPane.showMessageDialog(null, "Preencha todos os campos!!");
      } 
      else{
      
          funcionario = new Funcionario();
          funcionario.setNomeFuncionario(txt_nomeFuncionario.getText());
          funcionario.setNum_carteiraFuncionario(txt_num_carteiraFuncionario.getText());
          funcionario.setTipoFuncionario(txt_funcaoFuncionario.getText());
          funcionario.setFoneFuncionario(txt_foneFuncionario.getText());
          funcionario.setEmailFuncionario(txt_emailFuncionario.getText());
          funcionario.setSenhaFuncionario(Integer.parseInt(txt_senhaFuncionario.getText()));
          
          try {
              funcionarioDAO.Cadastrar(funcionario);
              
              
          } catch (SQLException ex) {
              Logger.getLogger(FuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
          }
          JOptionPane.showMessageDialog(null, "Cadastro de funcionário realizado com sucesso");
          atualizarTabelaFuncionario();
          atualizaUsuario();
          preparaSalvareCancelar();
          desativaCampos();
          LimpaCamposFuncionario();
       }
      
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    
    
    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        // TODO add your handling code here:
        LimpaCamposFuncionario();
        preparaSalvareCancelar();
    }//GEN-LAST:event_btn_LimparActionPerformed

    
    
    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        // TODO add your handling code here:
        if(txt_idFuncionario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Seleciona um funcionario!!");
        }
        else{
        
            funcionario = new Funcionario();
            funcionario.setCodFuncionario(Integer.parseInt(txt_idFuncionario.getText()));
            int confirma = JOptionPane.showConfirmDialog(null,"Deseja Excluir: " + txt_nomeFuncionario.getText());
            if(confirma ==0){
                try {
                    funcionarioDAO.Excluir(funcionario);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(FuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!!");
                LimpaCamposFuncionario();
                atualizarTabelaFuncionario();
            }
        }
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    
    
    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        // TODO add your handling code here:
        if(txt_idFuncionario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um Funcionario");
        }
        else if(txt_nomeFuncionario.getText().isEmpty() || txt_num_carteiraFuncionario.getText().isEmpty()
        || txt_funcaoFuncionario.getText().isEmpty() || txt_foneFuncionario.getText().isEmpty() || txt_emailFuncionario.getText().isEmpty()
        || txt_senhaFuncionario.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para realizar a alteração!!");
        }
        else{
        
            funcionario = new Funcionario();
            funcionario.setNomeFuncionario(txt_nomeFuncionario.getText());
            funcionario.setNum_carteiraFuncionario(txt_num_carteiraFuncionario.getText());
            funcionario.setTipoFuncionario(txt_funcaoFuncionario.getText());
            funcionario.setFoneFuncionario(txt_foneFuncionario.getText());
            funcionario.setEmailFuncionario(txt_emailFuncionario.getText());
            funcionario.setSenhaFuncionario(Integer.parseInt(txt_senhaFuncionario.getText()));
            funcionario.setCodFuncionario(Integer.parseInt(txt_idFuncionario.getText()));
            try {
                funcionarioDAO.Alterar(funcionario);
            } catch (SQLException ex) {
                Logger.getLogger(FuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
            }
            LimpaCamposFuncionario();
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!!");
            atualizaUsuario();
            atualizarTabelaFuncionario();
            preparaSalvareCancelar();
            desativaCampos();
        }
    }//GEN-LAST:event_btn_EditarActionPerformed

    
    
    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
        String cod = JOptionPane.showInputDialog("Digite o codigo do funcionario: ");
        funcionario = new Funcionario();
        try {
            funcionario = funcionarioDAO.buscaFuncionarioCodigo(cod);
        } catch (SQLException ex) {
            Logger.getLogger(FuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txt_nomeFuncionario.setText(funcionario.getNomeFuncionario());
        txt_num_carteiraFuncionario.setText(funcionario.getNum_carteiraFuncionario());
        txt_funcaoFuncionario.setText(funcionario.getTipoFuncionario());
        txt_foneFuncionario.setText(funcionario.getFoneFuncionario());
        txt_emailFuncionario.setText(funcionario.getEmailFuncionario());
        txt_senhaFuncionario.setText(String.valueOf(funcionario.getSenhaFuncionario()));
        
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void tbl_FuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_FuncionarioMouseClicked
        // TODO add your handling code here:
        txt_idFuncionario.setText(tbl_Funcionario.getValueAt(tbl_Funcionario.getSelectedRow(), 0).toString());
        txt_nomeFuncionario.setText(tbl_Funcionario.getValueAt(tbl_Funcionario.getSelectedRow(), 1).toString());
        txt_num_carteiraFuncionario.setText(tbl_Funcionario.getValueAt(tbl_Funcionario.getSelectedRow(), 2).toString());
        txt_funcaoFuncionario.setText(tbl_Funcionario.getValueAt(tbl_Funcionario.getSelectedRow(), 3).toString());
        txt_foneFuncionario.setText(tbl_Funcionario.getValueAt(tbl_Funcionario.getSelectedRow(), 4).toString());
        txt_emailFuncionario.setText(tbl_Funcionario.getValueAt(tbl_Funcionario.getSelectedRow(), 5).toString());
        txt_senhaFuncionario.setText(tbl_Funcionario.getValueAt(tbl_Funcionario.getSelectedRow(), 6).toString());
        preparaSelecaoTabela();
    }//GEN-LAST:event_tbl_FuncionarioMouseClicked

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
        LimpaCamposFuncionario();
        preparaNovo();
        ativaCampos();
    }//GEN-LAST:event_btn_novoActionPerformed

    
    
    private void atualizarTabelaFuncionario(){
    
        funcionario = new Funcionario();
        try {
            listaFuncionario = funcionarioDAO.ListaFuncionario();
        } catch (SQLException ex) {
            Logger.getLogger(FuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String dados[][] = new String[listaFuncionario.size()][7];
        int i = 0;
        
        for(Funcionario funcionario : listaFuncionario){
        
            dados[i][0] = String.valueOf(funcionario.getCodFuncionario());
            dados[i][1] = funcionario.getNomeFuncionario();
            dados[i][2] = funcionario.getNum_carteiraFuncionario();
            dados[i][3] = funcionario.getTipoFuncionario();
            dados[i][4] = funcionario.getFoneFuncionario();
            dados[i][5] = funcionario.getEmailFuncionario();
            dados[i][6] = String.valueOf(funcionario.getSenhaFuncionario());
            i++;
        }
        String tituloColuna[] = {"id","Nome","Numero_Carteira","Função","Fone","Email","Senha"};
        DefaultTableModel tabelaFuncionario = new DefaultTableModel();
        tabelaFuncionario.setDataVector(dados, tituloColuna);
        tbl_Funcionario.setModel(new DefaultTableModel(dados,tituloColuna){
        
            boolean[] canEdit = new boolean[]{
            
                false,false,false,false,false,false,false
            };
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        });
        
        tbl_Funcionario.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbl_Funcionario.getColumnModel().getColumn(1).setPreferredWidth(600);
        tbl_Funcionario.getColumnModel().getColumn(2).setPreferredWidth(300);
        tbl_Funcionario.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbl_Funcionario.getColumnModel().getColumn(4).setPreferredWidth(200);
        tbl_Funcionario.getColumnModel().getColumn(5).setPreferredWidth(500);
        tbl_Funcionario.getColumnModel().getColumn(6).setPreferredWidth(200);
        
        
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        tbl_Funcionario.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tbl_Funcionario.setRowHeight(25);
        tbl_Funcionario.updateUI();
    }
    
    private void atualizaUsuario(){
    
        usuarioDAO = new UsuarioDAO();
        try {
            usuarioDAO.cadastraUser();
        } catch (SQLException ex) {
            Logger.getLogger(FuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LimpaCamposFuncionario(){
    
        txt_idFuncionario.setText("");
        txt_nomeFuncionario.setText("");
        txt_num_carteiraFuncionario.setText("");
        txt_funcaoFuncionario.setText("");
        txt_foneFuncionario.setText("");
        txt_emailFuncionario.setText("");
        txt_senhaFuncionario.setText("");
        
    }
    
    public void ativaCampos(){
    
        
        txt_nomeFuncionario.setEnabled(true);
        txt_num_carteiraFuncionario.setEnabled(true);
        txt_funcaoFuncionario.setEnabled(true);
        txt_foneFuncionario.setEnabled(true);
        txt_emailFuncionario.setEnabled(true);
        txt_senhaFuncionario.setEnabled(true);
    }
    
    public void desativaCampos(){
    
       txt_idFuncionario.setEnabled(false);
       txt_nomeFuncionario.setEnabled(false);
       txt_num_carteiraFuncionario.setEnabled(false);
       txt_funcaoFuncionario.setEnabled(false);
       txt_foneFuncionario.setEnabled(false);
       txt_emailFuncionario.setEnabled(false);
       txt_senhaFuncionario.setEnabled(false); 
    }
    
    public void preparaNovo(){
    
        btn_novo.setEnabled(false);
        btn_Cadastrar.setEnabled(true);
        btn_Limpar.setEnabled(true);
        btn_Editar.setEnabled(false);
        tbl_Funcionario.setEnabled(false);
        tbl_Funcionario.clearSelection();
    }
    
    public void preparaSalvareCancelar(){
     
        btn_novo.setEnabled(true);
        btn_Cadastrar.setEnabled(false);
        btn_Limpar.setEnabled(false);
        btn_Editar.setEnabled(false);
        btn_Excluir.setEnabled(false);
        tbl_Funcionario.setEnabled(true);
    }
    
    public void preparaSelecaoTabela(){
    
        btn_novo.setEnabled(true);
        btn_Excluir.setEnabled(true);
        btn_Editar.setEnabled(true);
        btn_Limpar.setEnabled(true);
        ativaCampos();
    }
     
    
   
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_novo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JPanel pnl_Funcionario;
    private javax.swing.JTable tbl_Funcionario;
    private javax.swing.JTextField txt_emailFuncionario;
    private javax.swing.JFormattedTextField txt_foneFuncionario;
    private javax.swing.JTextField txt_funcaoFuncionario;
    private javax.swing.JTextField txt_idFuncionario;
    private javax.swing.JTextField txt_nomeFuncionario;
    private javax.swing.JFormattedTextField txt_num_carteiraFuncionario;
    private javax.swing.JPasswordField txt_senhaFuncionario;
    // End of variables declaration//GEN-END:variables
}
