/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Model.Usuario;
import javax.swing.JFrame;

/**
 *
 * @author joaop
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form pRINCIPAL
     */
    public PrincipalView(Usuario usuario) {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Principal = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMenu = new javax.swing.JMenu();
        mniClientes = new javax.swing.JMenuItem();
        mniProdutos = new javax.swing.JMenuItem();
        mniFuncionarios = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenu();
        mniSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial", 1, 90)); // NOI18N
        label1.setText("P.D.V");

        javax.swing.GroupLayout pnl_PrincipalLayout = new javax.swing.GroupLayout(pnl_Principal);
        pnl_Principal.setLayout(pnl_PrincipalLayout);
        pnl_PrincipalLayout.setHorizontalGroup(
            pnl_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        );
        pnl_PrincipalLayout.setVerticalGroup(
            pnl_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        mnuMenu.setText("Menu");

        mniClientes.setText("Clientes");
        mniClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClientesActionPerformed(evt);
            }
        });
        mnuMenu.add(mniClientes);

        mniProdutos.setText("Produtos");
        mniProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProdutosActionPerformed(evt);
            }
        });
        mnuMenu.add(mniProdutos);

        mniFuncionarios.setText("Funcionários");
        mniFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFuncionariosActionPerformed(evt);
            }
        });
        mnuMenu.add(mniFuncionarios);

        jMenuBar1.add(mnuMenu);

        mnuSair.setText("Sair");

        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        mnuSair.add(mniSair);

        jMenuBar1.add(mnuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClientesActionPerformed
        // TODO add your handling code here:
        ClienteView clienteview = new ClienteView();
        pnl_Principal.removeAll();
        pnl_Principal.add(clienteview);
        pnl_Principal.updateUI();
    }//GEN-LAST:event_mniClientesActionPerformed

    private void mniProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProdutosActionPerformed
        // TODO add your handling code here:
        ProdutoView produtoview = new ProdutoView();
        pnl_Principal.removeAll();
        pnl_Principal.add(produtoview);
        pnl_Principal.updateUI();
    }//GEN-LAST:event_mniProdutosActionPerformed

    private void mniFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFuncionariosActionPerformed
        // TODO add your handling code here:
        FuncionarioView funcionarioview = new FuncionarioView();
        pnl_Principal.removeAll();
        pnl_Principal.add(funcionarioview);
        pnl_Principal.updateUI();
    }//GEN-LAST:event_mniFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Label label1;
    private javax.swing.JMenuItem mniClientes;
    private javax.swing.JMenuItem mniFuncionarios;
    private javax.swing.JMenuItem mniProdutos;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenu mnuMenu;
    private javax.swing.JMenu mnuSair;
    private javax.swing.JPanel pnl_Principal;
    // End of variables declaration//GEN-END:variables
}
