/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author joaop
 */
public class VendedorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form VendedorView
     */
    public VendedorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo_Vendedor = new javax.swing.JTextField();
        txtNome_Vendedor = new javax.swing.JTextField();
        txtSenha_Vendedor = new javax.swing.JTextField();
        txtNum_Carteira = new javax.swing.JTextField();
        txtFone_Vendedor = new javax.swing.JTextField();
        txtEmail_Vendedor = new javax.swing.JTextField();
        btnSalvar_Vendedor = new javax.swing.JButton();
        btnExcluir_Vendedor = new javax.swing.JButton();
        btnAlterar_Vendedor = new javax.swing.JButton();
        btnBuscar_Vendedor = new javax.swing.JButton();
        btnLimpar_Campos = new javax.swing.JButton();

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Senha:");

        jLabel4.setText("Nº da Carteira:");

        jLabel5.setText("Telefone:");

        jLabel6.setText("Email:");

        txtCodigo_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo_VendedorActionPerformed(evt);
            }
        });

        txtNome_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome_VendedorActionPerformed(evt);
            }
        });

        txtSenha_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenha_VendedorActionPerformed(evt);
            }
        });

        txtNum_Carteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum_CarteiraActionPerformed(evt);
            }
        });

        txtFone_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFone_VendedorActionPerformed(evt);
            }
        });

        txtEmail_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail_VendedorActionPerformed(evt);
            }
        });

        btnSalvar_Vendedor.setBackground(new java.awt.Color(0, 153, 51));
        btnSalvar_Vendedor.setText("Salvar");
        btnSalvar_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar_VendedorActionPerformed(evt);
            }
        });

        btnExcluir_Vendedor.setBackground(new java.awt.Color(51, 255, 255));
        btnExcluir_Vendedor.setText("Excluir");
        btnExcluir_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir_VendedorActionPerformed(evt);
            }
        });

        btnAlterar_Vendedor.setBackground(new java.awt.Color(51, 255, 255));
        btnAlterar_Vendedor.setText("Alterar");
        btnAlterar_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterar_VendedorActionPerformed(evt);
            }
        });

        btnBuscar_Vendedor.setBackground(new java.awt.Color(102, 255, 255));
        btnBuscar_Vendedor.setText("Buscar");
        btnBuscar_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_VendedorActionPerformed(evt);
            }
        });

        btnLimpar_Campos.setBackground(new java.awt.Color(255, 51, 51));
        btnLimpar_Campos.setForeground(new java.awt.Color(51, 51, 51));
        btnLimpar_Campos.setText("Limpar");
        btnLimpar_Campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar_CamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnExcluir_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(btnAlterar_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpar_Campos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFone_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNum_Carteira, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSenha_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtCodigo_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNome_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSenha_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNum_Carteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFone_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar_Campos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigo_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo_VendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo_VendedorActionPerformed

    private void txtNome_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome_VendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome_VendedorActionPerformed

    private void txtSenha_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenha_VendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha_VendedorActionPerformed

    private void txtNum_CarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum_CarteiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum_CarteiraActionPerformed

    private void txtFone_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFone_VendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFone_VendedorActionPerformed

    private void txtEmail_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail_VendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail_VendedorActionPerformed

    
    
    
    
    
    
    private void btnSalvar_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar_VendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvar_VendedorActionPerformed

    private void btnExcluir_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir_VendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluir_VendedorActionPerformed

    private void btnAlterar_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterar_VendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterar_VendedorActionPerformed

    private void btnBuscar_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar_VendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar_VendedorActionPerformed

    private void btnLimpar_CamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar_CamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpar_CamposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar_Vendedor;
    private javax.swing.JButton btnBuscar_Vendedor;
    private javax.swing.JButton btnExcluir_Vendedor;
    private javax.swing.JButton btnLimpar_Campos;
    private javax.swing.JButton btnSalvar_Vendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCodigo_Vendedor;
    private javax.swing.JTextField txtEmail_Vendedor;
    private javax.swing.JTextField txtFone_Vendedor;
    private javax.swing.JTextField txtNome_Vendedor;
    private javax.swing.JTextField txtNum_Carteira;
    private javax.swing.JTextField txtSenha_Vendedor;
    // End of variables declaration//GEN-END:variables
}
